Repository car-racer4/Bulls-and-Cow, pull requests merged in 2023-05, with the labels that each got.

#5 feat: Creat Bull-and-Cows.py
  Bulls-and-Cow.py
Labels: status: Done, Priority: High, Domain: Python

#6 feat: add bull, cow conuter
  Bulls-and-Cow.py
Labels: status: Done, Priority: medium, Domain: Python

#9 숫자 4개 입력 기능 구현
  Bulls-and-Cow.py
Labels: Type: Enhancement, status: Done, Priority: medium, Domain: Python
